on: [push]

name: Continuous integration

jobs:
  check-client:
    name: Check client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path client/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path client/Cargo.toml


  test-client:
    name: Test Suite client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path client/Cargo.toml
          
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path client/Cargo.toml


  fmt-client:
    name: Rustfmt client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path client/Cargo.toml

      - run: rustup component add rustfmt
        working-directory: ./client
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --manifest-path client/Cargo.toml

  clippy-client:
    name: Clippy client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path client/Cargo.toml

      - run: rustup component add clippy
        working-directory: ./client
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --manifest-path client/Cargo.toml
